<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активный',
    'Banned' => 'Заблокирован',
    'Created At' => 'Дата создания',
    'Email' => 'Электронная почта',
    'Inactive' => 'Неактивный',
    'Invalid old password' => 'Неверный старый пароль',
    'Invalid username or password' => 'Неверное имя или пароль',
    'Name' => 'Имя',
    'New Email' => 'Новая почта',
    'New password' => 'Новый пароль',
    'Old Email' => 'Старая почта',
    'Old password' => 'Старый пароль',
    'Password' => 'Пароль',
    'Password Repeat' => 'Пароль повторно',
    'Remember me' => 'Запомнить меня',
    'Retype new password' => 'Повторите новый пароль',
    'Retype password' => 'Повторите пароль',
    'Status ID' => 'Статус',
    'Surname' => 'Фамилия',
    'Token' => 'Ключ',
    'Updated At' => 'Дата обновления',
    'Username' => 'Логин',
];
