<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm' => 'Подтвердить',
    'Create account failed. Please try again later.' => '',
    'Email resend' => 'Отправка письма',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => '',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => '',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => '',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => '',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => '',
    'FRONTEND_FLASH_FAIL_RECOVERY' => '',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => '',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => '',
    'FRONTEND_FLASH_FAIL_UPDATE' => '',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => '',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => '',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => '',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => '',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => '',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => '',
    'FRONTEND_FLASH_SUCCES_UPDATE' => '',
    'Failed reset password. Try again later.' => 'Ошибка сброса пароля. Попробуйте позже',
    'Failed send email with activation code. Please try again later.' => 'Не удалось отправить письмо с кодом активации. Пожалуйста попробуйте позднее.',
    'Invalid recovery code' => 'Неверный код восстановления',
    'Login' => 'Вход',
    'Message with reset code was sent to specified e-mail.' => '',
    'On the specified email address was sent a letter with an activation code for new account.' => '',
    'Password recovery' => 'Восстановление пароля',
    'Password recovery confirm' => 'Подтверждение восстановления пароля',
    'Recovery' => 'Восстановить',
    'Recovery password' => 'Пароль восстановления',
    'Register account' => 'Зарегистрироваться',
    'Resend' => 'Отправить повторно',
    'Resend email' => 'Отправить письмо повторно',
    'Sending email failed. Try again later.' => 'Не удалось отправить письмо. Попробуйте позже',
    'Sign up' => 'Регистрация',
    'Success! Password was changed' => '',
    'Your account has been created successfully.' => '',
    'Your account has been created successfully. An email has been sent to you with detailed instructions.' => '',
    'or' => '',
];
