<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_CREATE_PLACEHOLDER_NAME' => '',
    'BACKEND_CREATE_SUBMIT' => '',
    'BACKEND_CREATE_SUBTITLE' => '',
    'BACKEND_CREATE_TITLE' => '',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => '',
    'BACKEND_FLASH_FAIL_ADMIN_DISABLE' => '',
    'BACKEND_FLASH_FAIL_ADMIN_ENABLE' => '',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => '',
    'BACKEND_INDEX_SUBTITLE' => '',
    'BACKEND_INDEX_TITLE' => '',
    'BACKEND_PROMPT_MODEL_CLASS' => '',
    'BACKEND_PROMPT_STATUS' => '',
    'BACKEND_UPDATE_SUBMIT' => '',
    'BACKEND_UPDATE_SUBTITLE' => '',
    'BACKEND_UPDATE_TITLE' => '',
];
