<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<a href="{login}">Login</a> or <a href="{register}">register</a> to post comments' => '',
    'FRONTEND_FLASH_FAIL_CREATE' => '',
    'FRONTEND_FLASH_FAIL_DELETE' => '',
    'FRONTEND_FLASH_FAIL_UPDATE' => '',
    'FRONTEND_FLASH_RECORD_NOT_FOUND' => '',
    'FRONTEND_WIDGET_COMMENTS_DELETE' => '',
    'FRONTEND_WIDGET_COMMENTS_DELETED_COMMENT_TEXT' => '',
    'FRONTEND_WIDGET_COMMENTS_DELETE_CONFIRMATION' => '',
    'FRONTEND_WIDGET_COMMENTS_FORM_SUBMIT' => '',
    'FRONTEND_WIDGET_COMMENTS_REPLY' => '',
    'FRONTEND_WIDGET_COMMENTS_UPDATE' => '',
    'Post comment' => '',
];
