<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_AUTHOR' => '',
    'ATTR_CONTENT' => '',
    'ATTR_CREATED' => '',
    'ATTR_ID' => '',
    'ATTR_MODEL' => '',
    'ATTR_MODEL_CLASS' => '',
    'ATTR_NAME' => '',
    'ATTR_PARENT' => '',
    'ATTR_STATUS' => '',
    'ATTR_UPDATED' => '',
    'ERROR_MSG_INVALID_MODEL_ID' => '',
    'STATUS_ACTIVE' => '',
    'STATUS_BANNED' => '',
    'STATUS_DELETED' => '',
    'STATUS_DISABLED' => '',
    'STATUS_ENABLED' => '',
];
