<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<a href="{login}">Login</a> or <a href="{register}">register</a> to post comments' => '<a href="{login}">Войдите</a> или <a href="{register}">зарегистрируйтесь</a> чтобы оставлять комментарии',
    'FRONTEND_FLASH_FAIL_CREATE' => 'Не удалось сохранить комментарий. Попробуйте пожалуйста еще раз!',
    'FRONTEND_FLASH_FAIL_DELETE' => 'Не удалось удалить комментарий. Попробуйте пожалуйста еще раз!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Не удалось обновить комментарий. Попробуйте пожалуйста еще раз!',
    'FRONTEND_FLASH_RECORD_NOT_FOUND' => 'Ошибка 404 - страница не найдена!',
    'FRONTEND_WIDGET_COMMENTS_DELETE' => 'Удалить',
    'FRONTEND_WIDGET_COMMENTS_DELETED_COMMENT_TEXT' => 'Комментарий был удалён',
    'FRONTEND_WIDGET_COMMENTS_DELETE_CONFIRMATION' => 'Вы уверены что хотите удалить этот комментарий?',
    'FRONTEND_WIDGET_COMMENTS_FORM_SUBMIT' => 'Опубликовать комментарий',
    'FRONTEND_WIDGET_COMMENTS_REPLY' => 'Ответить',
    'FRONTEND_WIDGET_COMMENTS_UPDATE' => 'Редактировать',
    'Post comment' => 'Написать комментарий',
];
