<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_AUTHOR' => 'Автор',
    'ATTR_CONTENT' => 'Контент',
    'ATTR_MODEL' => 'Модель',
    'ATTR_MODEL_CLASS' => 'Класс модели разрешения',
    'ATTR_PARENT' => 'Родитель',
    'ERROR_MSG_INVALID_MODEL_ID' => 'Неверный ID модели',
    'STATUS_ACTIVE' => 'Активный',
    'STATUS_BANNED' => 'Заблокирован',
    'STATUS_DELETED' => 'Удален',
    'ATTR_CREATED' => 'Дата создания',
    'ATTR_ID' => '№',
    'ATTR_NAME' => 'Модель',
    'ATTR_STATUS' => 'Стату',
    'ATTR_UPDATED' => 'Дата обновления',
    'STATUS_DISABLED' => 'Отключён',
    'STATUS_ENABLED' => 'Включён',
];
