<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm' => 'Подтвердить',
    'Create user' => 'Создать пользователя',
    'I forgot my password' => 'Я ззабыл свой пароль',
    'Login' => 'Войти',
    'Main Information' => 'Основная информация',
    'Recover password' => 'Восстановить пароль',
    'Select status' => 'Выбрать статус',
    'Sign in to start your session' => 'Войдите чтобы начать',
    'Update user' => 'Обновить пользователя',
    'Use login' => 'Использовать логин',
];
